<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="H2400-0383L" name="com.perficient.test.cat.pccaurora.testcase.quickorder.TC2093_Tc011QuickOrderSpecialCharacters" tests="1" failures="0" timestamp="11 Nov 2016 07:07:34 GMT" time="166.866" errors="1">
  <testcase name="verify_TC2093_Tc011QuickOrderSpecialCharacters" time="166.866" classname="com.perficient.test.cat.pccaurora.testcase.quickorder.TC2093_Tc011QuickOrderSpecialCharacters">
    <error type="java.lang.AssertionError" message="actual size:4 expected [13] but found [4]">
      <![CDATA[java.lang.AssertionError: actual size:4 expected [13] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.perficient.test.cat.pccaurora.testcase.quickorder.TC2093_Tc011QuickOrderSpecialCharacters.verify_TC2093_Tc011QuickOrderSpecialCharacters(TC2093_Tc011QuickOrderSpecialCharacters.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </error>
  </testcase> <!-- verify_TC2093_Tc011QuickOrderSpecialCharacters -->
</testsuite> <!-- com.perficient.test.cat.pccaurora.testcase.quickorder.TC2093_Tc011QuickOrderSpecialCharacters -->
